[package]
name = "librecard"
version = "0.1.0"
edition = "2024"
authors = ["Yi Cao <yi@ycao.net>"]
publish = false

[dependencies]

twox-hash = "2.1.0"

eframe = { version = "0.31.1", features = ["default"] }
rfd = "0.15.3"
