[package]
name = "librecard"
version = "0.1.0"
edition = "2024"
authors = ["Yi Cao <yi@ycao.net>"]
publish = false

[dependencies]

xxhash-rust = {version = "0.8.15", features = ["xxh3", "std"]}

eframe = { version = "0.31.1", features = ["default"] }
rfd = "0.15.3"
