[package]
name = "librecard"
version = "0.1.0"
edition = "2024"
authors = ["Yi Cao <yi@ycao.net>"]
publish = false

[dependencies]

twox-hash = { version = "2.1.0", features = ["xxhash3_64", "std"] }
csv = "1.3.1"

eframe = { version = "0.31.1", features = ["default"] }
rfd = "0.15.3"
